import sys,json,shutil,hashlib
from pathlib import Path
R=Path('/home/wqz/real2sim_whole_scene_20260926');sys.path.insert(0,str(R/'repo/workflow'))
from r2s.core import Workflow,atomic_json
w=Workflow(R/'case');out=Path(w.state['stages']['agent_identify']['directory'])
shutil.copyfile(R/'evidence/bruksvara_hk_0.jpg',out/'bruksvara_product.jpg')
url='https://www.ikea.com.hk/en/products/wardrobes-and-chest-of-drawers/wardrobes/bruksvara-art-90556047'
atomic_json(out/'catalogue.json',dict(retrieved='2026-09-26',branch='A',records=[dict(entity='wardrobe',candidate='IKEA BRUKSVARA 905.560.47 white',identity='visually consistent candidate; not label verified',confidence=.82,dimensions_m=[.794,.565,2.01],measurement_role='conditional reconstruction prior, not validation truth',source=url,image='bruksvara_product.jpg',image_url='https://www.ikea.com.hk/dairyfarm/hk/images/788/1178845_PE895737_S4.jpg',image_sha256=hashlib.sha256((out/'bruksvara_product.jpg').read_bytes()).hexdigest(),manufacturer_image_review='consistent',findings='Inspected actual 500x500 official photo: long left plain door, right shorter plain door, exactly two bottom-right drawers, four pale round knobs and narrow plinth. All visible topology agrees; source lens and handle appearance differ slightly.'),dict(entity='shoe_cabinet',identity='unknown',queries=['IKEA shoe cabinet two drawers two doors open right shelves','HEMNES shoe cabinet'],rejected_candidates=[dict(candidate='HEMNES 2 compartment',reason='Catalogue describes two flip compartments, inconsistent with two small top drawers plus tall hinged doors and open right column')],dimensions_m=None,decision='independent image fit; no catalogue dimension adopted',uncertainty='Manufacturer unidentified. Faint door lines not sufficient for louvred relief.'),dict(entity='bed',identity='unknown wooden shelf headboard bed',length_prior_m=2,source='user confirmed longitudinal rail',decision='independent geometry; no external mesh')]))
atomic_json(out/'assets.json',dict(branch='A',external_geometry=[],policy='No external furniture geometry or historical scene assets read.',product_images=['bruksvara_product.jpg'],textures='Will author inferred whole-object materials after accepted geometry'))
atomic_json(out/'response.json',dict(status='complete',artifacts=['catalogue.json','assets.json','bruksvara_product.jpg'],evidence=[url,'actual official product photo inspected'],reasoning_summary='BRUKSVARA is a topology-consistent candidate with conditional official dimensions. Shoe cabinet and bed remain unidentified; only user bed length is confirmed.'))
print(w.accept('agent_identify',out/'response.json'));print(w.run())
