import sys,json,shutil
from pathlib import Path
from PIL import Image
R=Path('/home/wqz/real2sim_whole_scene_20260926');sys.path.insert(0,str(R/'repo/workflow'));from r2s.core import Workflow,atomic_json
w=Workflow(R/'case');assert not (R/'case/runs/run.lock').exists();old=Path(w.state['stages']['agent_observe']['directory']);response=json.loads((old/'response.json').read_text());w.revise('agent_observe','Whole-scene review identified the visible white flush ceiling insert; expand fixture observation without dropping targets or resetting comparisons.');print(w.run());out=Path(w.state['stages']['agent_observe']['directory'])
for name in response['artifacts']:shutil.copyfile(old/name,out/name)
obs=json.loads((out/'observation.json').read_text());box=[810,0,1674,280];target=next(t for t in obs['appearance_targets'] if t['entity']=='ceiling_fixtures');target['source_crop_xyxy']=box;target['features'].append('Bright flush quadrilateral insert near image centre, distinct from vent/sprinkler/round fitting; possible diffuser or replacement panel.');target['appearance']['uncertainty']+=' White insert identity and powered state unknown; use a non-emissive pale surface hypothesis.'
measure=json.loads((R/'evidence/ceiling_measurements.json').read_text());obs['ceiling_white_panel']=dict(source_polygon_xy=measure['panel_polygon_xy'],interpretation='Observed flat white insert/diffuser surface. No measured protrusion or electrical state; non-emissive flush appearance region.',evidence='ceiling_panel_detection.jpg')
surface=json.loads((out/'surface_observation.json').read_text());region=next(r for r in surface['regions'] if r['entity']=='ceiling_fixtures');region['source_box_xyxy']=box;region['pattern']+=' Also one white flush insert/diffuser near image centre.';region['features'].append(dict(id='ceiling_white_panel',description='Whiter flush quadrilateral within ceiling grid; depth and electrical function are unresolved.',classification='uncertain',alternatives=['Unlit white luminaire diffuser','Lighter replacement or access panel']))
Image.open(obs['appearance_source']['path']).convert('RGB').crop(box).save(out/region['source_crop']);shutil.copyfile(R/'evidence/ceiling_panel_detection.jpg',out/'ceiling_panel_detection.jpg');response['artifacts'].append('ceiling_panel_detection.jpg');response['reasoning_summary']='Rechecked entire ceiling. Existing 13 targets retained; fixture crop now includes the visible white flush panel. Only an appearance surface is inferred, with no unsupported depth or on-state claim.';atomic_json(out/'observation.json',obs);atomic_json(out/'surface_observation.json',surface);atomic_json(out/'response.json',response);print(w.accept('agent_observe',out/'response.json'))
