import json,sys,hashlib
from pathlib import Path
from PIL import Image
R=Path('/home/wqz/real2sim_whole_scene_20260926');sys.path.insert(0,str(R/'repo/workflow'))
from r2s.core import Workflow,atomic_json
w=Workflow(R/'case');out=Path(w.state['stages']['agent_observe']['directory']);p=json.loads((out/'packet.json').read_text());source=p['appearance_source'];im=Image.open(source['path']).convert('RGB')
# Pixel observations authored from the complete original in this run; no prior scene consulted.
specs=[
('floor',[0,717,1702,1276],False,'Dark taupe grey carpet tiles; alternating orthogonal fine streak direction, broad irregular light from window.','Tile seams are flat; no raised grid.','albedo'),
('ceiling',[0,0,1702,321],False,'Off-white suspended tile grid with darker thin seams and a rectangular slotted vent at upper right.','Tile seams have weak relief, not deep carved panels.','uncertain'),
('wall_back',[834,130,1702,923],False,'Plain near-white rear wall; darker at right, light reflected near bed.','Continuous painted surface; shadows do not define albedo stripes.','albedo'),
('wall_left',[0,0,335,633],False,'Near-white solid wall segment beside window.','Large plain plane bounded by the window reveal.','albedo'),
('window',[292,79,846,843],False,'Dark charcoal frames, three upper bays and closely spaced lower protective vertical rails.','Three dark full-height framing boundaries plus lower rails; count lower rails separately from reflected exterior.','uncertain'),
('blinds',[293,92,843,540],True,'Three taupe-grey flat roller blinds with different hem elevations, narrow luminous gaps and bead pull cords.','Three distinct opaque roll-down panels; nearly planar taut fabric, not draped curtains.','geometry'),
('bed',[619,610,1147,1018],True,'Honey wood frame; blue-grey fitted sheet; pale ivory and sage dense botanical duvet; one broad pillow, small pastel toys along head shelf.','Wood frame has two rectangular inset head panels and top shelf; duvet broad asymmetric folds, side drape and no uniform quilting grid.','uncertain'),
('shoe_cabinet',[0,605,490,1080],False,'Off-white cabinet with two top drawers, two framed doors and narrow right open column containing footwear.','Horizontal faint lines inside door panels are ambiguous; do not construct a dense louvre grill.','uncertain'),
('wardrobe',[1230,301,1675,1020],False,'Plain white asymmetric two-door wardrobe; left long door and right short door above two drawers, paired small oval pale handles.','Four distinct large front panels: two doors and two right-bottom drawers. No decorative recessed grooves.','geometry'),
('reflective_board',[946,390,1310,667],False,'Large pale glass-like wall board behind bed, with window reflections left and diffuse dull white right.','Reflected window streaks belong to illumination/reflection, not painted stripes.','lighting'),
('exterior',[340,491,839,805],False,'Sunlit green foliage, pale yellow railings and distant grey structure visible through exposed window portions.','Exterior structure depth and unreadable sign identity unknown; keep inferred scene restrained.','uncertain'),
('glass_partition',[1590,652,1702,1276],False,'Narrow near-camera cool grey glass/metal partition at right edge with pale reflection and dark thin trim.','Right edge is a separate foreground plane, not an extension of the wardrobe.','uncertain'),
('ceiling_fixtures',[1070,13,1674,221],False,'Ceiling vent, small sprinkler and round white ceiling fitting near upper-right crop.','Round fitting identity may be detector or recessed luminaire; retain conservative fixture geometry and infer unobserved lighting.','uncertain')]
targets=[];regions=[]
for entity,box,soft,palette,feature,kind in specs:
 crop=f'source_{entity}.png';im.crop(box).save(out/crop)
 targets.append(dict(entity=entity,source_crop_xyxy=box,whole_object=True,soft_surface=soft,features=[feature],appearance=dict(palette=palette,pattern_layout=feature,direction='Architectural and cabinet axes align locally; cloth motifs follow fabric UV, carpet streaks alternate by tile.',scale_evidence='Image proportions; bed longitudinal rail 2.0 m is the only user confirmed length. Other scales estimated.',uncertainty='Single image, hidden regions inferred; lighting cannot be uniquely separated from reflectance.')))
 f=dict(id=entity+'_feature',description=feature,classification=kind)
 if kind=='geometry':f.update(count=3 if entity=='blinds' else 4,depth_cues='Separate silhouettes, hem/panel edges and occlusion borders visible in original',confidence=.9)
 if kind=='uncertain':f['alternatives']=['Shallow geometric boundary where supported by silhouette','Albedo or illumination variation; omit unsupported relief']
 regions.append(dict(id='surface_'+entity,entity=entity,pattern=feature,source_box_xyxy=box,source_crop=crop,allow_repeated_relief=entity in ['window','ceiling','ceiling_fixtures'],features=[f]))
coverage=dict(architecture={'entities':['floor','ceiling','wall_back','wall_left']},openings={'entities':['window','glass_partition']},furniture={'entities':['bed','shoe_cabinet','wardrobe']},soft_objects={'entities':['bed','blinds']},reflective_surfaces={'entities':['reflective_board','glass_partition','window']},lighting={'entities':['ceiling_fixtures']},exterior={'entities':['exterior']})
atomic_json(out/'observation.json',dict(source_sha256=source['sha256'],appearance_source=source,pixel_convention='xy pixels; upper-left origin; authorized 1702x1276 unmodified image',evidence=['actual full original inspected by Agent','unchanged source crops'],appearance_targets=targets,scene_appearance=dict(global_palette='Low-saturation grey/ivory shell and furnishings, honey wood bed, pale sage fabric, localized pastel toys and green exterior.',light_distribution='Bright window left, high reflected patch behind headboard, dark floor foreground and wardrobe right side; ceiling comparatively dim.',contrast_hierarchy='Black window framing strongest edges; white wardrobe broad field; bed print low contrast; carpet fine contrast below furniture silhouettes.',uncertainties=['Exterior geometry not measurable','Hidden front/right wall extents unknown','Round ceiling fitting ambiguous'],coverage=coverage),occlusions=['Cabinet hides window lower left','Bed hides lower rear wall and sill','Wardrobe occludes right part of board','Right glass partition cuts off room edge'],scale_prior=dict(entity='bed',part='longitudinal_side_rail',length_m=2.0,source='user confirmation',role='reconstruction prior')))
landmarks={
'bed':[('foot_left_top',[629,797],'foot_frame'),('foot_right_top',[827,936],'foot_frame'),('foot_left_floor',[635,868],'left_foot'),('foot_right_floor',[820,1008],'right_foot'),('head_left_top',[946,621],'headboard'),('head_right_top',[1136,647],'headboard')],
'wardrobe':[('top_left',[1307,362],'carcass'),('top_right',[1668,312],'carcass'),('bottom_left',[1237,906],'carcass'),('bottom_right',[1520,1015],'carcass')],
'shoe_cabinet':[('top_right',[464,615],'carcass'),('bottom_right',[485,923],'carcass'),('door_right_top',[377,676],'doors'),('door_right_bottom',[402,951],'doors')]}
parts={'bed':['foot_frame','left_foot','right_foot','side_rails','headboard','slats','mattress','duvet','pillow','toys'],'wardrobe':['carcass','long_door','short_door','upper_drawer','lower_drawer','handles'],'shoe_cabinet':['carcass','doors','drawers','shelves','handles','footwear']}
fts=[]
for e,lms in landmarks.items():
 fts.append(dict(entity=e,parts=[dict(id=x,owner=e) for x in parts[e]],constraints=['Coherent local orthogonal frame','Continuous load path to floor','Panels remain connected to own carcass','No cross-furniture joins'],observations=[dict(id=e+'_'+i,uv=uv,part=part,visibility='observed') for i,uv,part in lms],uncertain=['Hidden joinery and rear feet inferred','Occluded dimensions are not independent measurements']))
atomic_json(out/'furniture_observation.json',dict(schema='real2sim.furniture-observation/1',source_sha256=source['sha256'],acceptance_before_fit=dict(landmark_median_px=9,landmark_max_px=18,major_silhouette_mismatch='blocking',surface_topology='blocking',whole_scene_regression='blocking',unexpected_interpenetration_tolerance_m=.006),targets=fts))
atomic_json(out/'surface_observation.json',dict(schema='real2sim.surface-observation/1',source_sha256=source['sha256'],regions=regions))
files=[x.name for x in out.iterdir() if x.suffix in ['.png','.json'] and x.name not in ['packet.json','response.json']]
atomic_json(out/'response.json',dict(status='complete',evidence=['authorized original inspected','13 full-extent appearance targets and unchanged crops'],reasoning_summary='Whole-scene appearance and structural observations authored from original; uncertain lines explicitly not geometric relief; all furniture identities remain candidates.',parameters={'dynamics':'off; static reconstruction'},artifacts=files))
print('accepted',w.accept('agent_observe',out/'response.json'));print(w.run())
