"""Submit an inspected light trial; leave visual acceptance to the final gate."""
import sys,json,shutil,hashlib,re
from pathlib import Path
R=Path('/home/wqz/real2sim_whole_scene_20260926');sys.path.insert(0,str(R/'repo/workflow'))
from r2s.core import Workflow,atomic_json
trial=sys.argv[1];assert re.fullmatch(r'lighting_rect_\d+',trial)
w=Workflow(R/'case');out=Path(w.state['stages']['agent_calibrate_lighting']['directory']);matdir=Path(w.state['stages']['agent_materials']['directory']);metrics=json.loads((out/'regional_light_metrics.json').read_text());setup=json.loads((out/'rect_trials.json').read_text());power=float(trial.rsplit('_',1)[1]);assert power in setup['area_power_W']
shutil.copyfile(out/(trial+'.blend'),out/'model.blend');shutil.copyfile(matdir/'scene.json',out/'scene.json');shutil.copyfile(out/(trial+'.png'),out/'lighting_selected.png')
record=dict(camera_locked=True,geometry_locked=True,material_parameters_locked=True,exposure_albedo_gauge_fixed=True,exposure=0,view_transform='AgX',accepted_material_sha256=hashlib.sha256((matdir/'model.blend').read_bytes()).hexdigest(),selected_trial=trial,lights=[dict(name='window_daylight',type='AREA',power_W=power,dimensions_m=[2.15,.80],position=setup['area_position'],direction=setup['area_direction'],interpretation=setup['proxy_ray_visibility']),dict(name='exterior_sun',energy=setup['sun_energy'],angle_rad=setup['sun_angle_rad']),dict(name='day_world',strength=setup['world_strength'])],comparison_before=['material_source_preview.png'],comparison_after=['lighting_selected.png'],metrics_before=metrics['mean_srgb_luminance']['material_source_preview.png'],metrics_after=metrics['mean_srgb_luminance'][trial+'.png'],uncertainty=['Source image alone cannot uniquely determine HDR environment, source power or material reflectance. Parameters are fitted hypotheses.','Regional luminance residuals are in-sample diagnostics, not independent reality accuracy.','Detailed exterior species, unseen structure and exact reflected microdetails remain inferred; final visual review must still judge the full scene.'],whole_scene_checks=dict(light_distribution='Window remains dominant; selected exterior/interior radiance ratio restores physical window reflection while keeping a dark carpet foreground and readable pale furniture.',shadow_direction='Compared original and trial: broad soft shadows remain below furniture and extend from the window side into the room.',reflection_strength='Actual window/blind/guard geometry appears in the rear board reflection after exterior radiance correction; no photo is painted onto the board and no metallic compensation is used.',contrast_hierarchy='Original and entire trial compared: dark window frame, pale cabinets and bedding, muted wooden bed and dark grey carpet retain their relative roles. Final acceptance is separately gated.'))
atomic_json(out/'lighting_calibration.json',record)
# Retain all trial models remotely; only the selected model is a dependency.
atomic_json(out/'trial_models_manifest.json',{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in out.glob('lighting_*.blend')})
files=[str(p.relative_to(out)) for p in out.rglob('*') if p.is_file() and p.name not in ['packet.json','response.json','record.json'] and (p.suffix!='.blend' or p.name=='model.blend')]
atomic_json(out/'response.json',dict(status='complete',artifacts=files,evidence=['lighting_selected.png','regional_light_metrics.json','rect_trials.json'],reasoning_summary='Selected actual inspected illumination trial after source-wide and regional comparison. Material nodes/assignments and geometry remained locked. Failed trials retained; final appearance acceptance remains for the executable render and review.'))
print(w.accept('agent_calibrate_lighting',out/'response.json'));print(w.run())
