"""Authored observations from the displayed original, before modelling; not automated inference."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def write_stage(stage,data,reason):
    out=ROOT/'evidence'/stage;out.mkdir(exist_ok=True,parents=True)
    for filename,value in data.items():(out/filename).write_text(json.dumps(value,indent=2,ensure_ascii=False))
    (out/'response.json').write_text(json.dumps(dict(status='complete',evidence=['inputs/utility_room_original.jpg (actually displayed and inspected)',*data.keys()],reasoning_summary=reason,parameters={'coordinate_convention':'original 1702x1276, pixels from top-left'},artifacts=list(data),issues=[]),indent=2))
objects=[
 ('column','rectangular structural pier',[[360,48],[515,154],[573,693],[465,725]],'floor-ceiling; two exposed faces; hides left window edge',.96),
 ('table','thin gray rectangular top and slender wood legs',[[615,576],[739,547],[849,556],[716,597]],'four legs touch floor; partly hides far chair',.95),
 ('chair_near','wood chair, curved low back, green padded seat',[[762,604],[861,589],[865,694],[833,739],[764,714]],'floor support; table behind upper left; back and arms partly ambiguous',.88),
 ('chair_far','second wood chair green seat',[[619,560],[674,556],[710,618],[701,691],[633,706]],'table occludes center; four legs inferred',.85),
 ('rack','tan narrow A-frame garment rack with low slatted shelf',[[1065,415],[1390,414],[1356,735],[1017,766]],'four feet; rail over garments',.94),
 ('garments','overlapping dark, teal, pale gray and red hanging clothes',[[1109,441],[1230,430],[1280,451],[1318,483],[1300,586],[1271,644],[1230,691],[1200,659],[1090,652]],'supported by hangers on rack; individual hidden layers uncertain',.93),
 ('cabinet','black freestanding ribbed-front box; exact function unknown',[[1238,634],[1456,668],[1524,753],[1450,1075],[1396,1110],[1164,994]],'floor-supported; in front of rack; no confirmed drawer/hinge mechanism',.87),
 ('cleaning_cart','gray wheeled cleaning trolley with paired refuse bins',[[0,562],[184,543],[229,590],[220,681],[310,681],[344,868],[379,900],[375,928],[156,1029]],'cropped by left doorway; wheels and frame; yellow warning sign',.9),
 ('wastebasket','small black bin under near table corner',[[640,678],[688,677],[696,696],[685,741],[656,746],[646,728]],'floor contact; liner crumpled rim',.92),
 ('door_leaf','partly open glass door at right with handle/keys',[[1701,762],[1586,1275],[1483,1275],[1610,838]],'door axis and full leaf extent mostly outside image; hardware visible',.78),
 ('window_back','large black-framed floor-height glazing with roller blinds',[[786,161],[1362,40],[1258,751],[784,668]],'railing at lower pane; upper right blind raised',.97),
 ('window_left','narrow return glazing with blind',[[518,161],[621,196],[635,639],[555,655]],'left edge occluded by column',.95),
 ('ceiling_luminaire','unseen ceiling panel light',[],'required complete-shell hypothesis; no visible luminous fixture identified',.1)]
obs=dict(schema='case.observation/1',source_sha256='dfe25afbfb885ae9bc377691dd18ebd4259ffa72917ca725e3809ef40624c29c',image_size=[1702,1276],pixel_convention='top-left x right y down',objects=[dict(id=i,description=d,outline_pixels=p,relations=r,confidence=c) for i,d,p,r,c in objects],room=dict(floor='gray modular carpet with alternating pile direction',ceiling='off-white suspended tile grid',back='main window wall with white pier at left',left='white wall and protruding column / short return glazing',right='white wall meeting window edge',front='mostly outside view; doorway margins visible'),lighting=dict(observed='bright daylight, lower window sun patch with crisp rail shadows, warm pale walls, dark clothing and cabinet',unknown='exact location/time, sky/sun strength, camera exposure and WB'),physics_candidates=dict(hinge='partly visible glass door, axis inferred',cloth='red outer garment on rack, hanger-pinned thin shell',soft_body='green chair seat has visible thin raised padded volume; foam interpretation provisional, test sensitivity required'),unknowns=['no camera EXIF','no exact furniture identity','no independent measured dimensions','no hidden-wall evidence','cabinet function/door mechanism unconfirmed','chair seat could instead be a thin removable pad; no measured elastic properties'])
protocol=dict(version='1.0',registered_before_geometry=True,resolution=[1702,1276],source_comparison='same camera, uncropped original; all errors are in-sample',geometry=dict(anchor_median_px_max=15,anchor_max_px_max=35,major_object_outline_typical_px_max=25,blocking='any major wrong topology, missing object, contact or occlusion, regardless of aggregate score'),materials=dict(blocking='plastic-looking cloth/carpet, major color or roughness discrepancy'),lighting=dict(blocking='incorrect dominant shadow direction or missing window illumination; compare source ROI medians with target absolute difference <=0.15 linear-normalized luminance where comparable'),completeness='four walls, floor, ceiling, luminaires retained in every candidate; invisible completion labelled',truth_status='no independent truth; no dimension accuracy certificate')
furniture=json.loads((ROOT/'case/furniture_observation.json').read_text());obs['part_observation']='furniture_observation.json';obs['revision_note']='Table and chair part ownership re-observed after user identified structural failures; old outline-only review was insufficient.'
write_stage('agent_observe',{'observation.json':obs,'acceptance_protocol.json':protocol,'furniture_observation.json':furniture},'Original inspected directly; annotated principal objects and detailed furniture ownership/visibility/constraints. Part observations are consumed by the builder. No old-case artifacts consulted.')
sources=[
 dict(id='CH20',url='https://www.carlhansen.com/en/en/collection/chairs/dining-chairs/ch20',query='CH20 elbow chair dimensions',retrieved='2026-09-22',findings='Official bent-wood backrest, upholstered seat; official 3D download links exist.',identity='unverified style candidate; no label, finish/seat variant or matching construction established',used_dimensions=None),
 dict(id='POANG',url='https://www.ikea.com/us/en/p/poaeng-armchair-birch-veneer-gunnared-light-green-s39501906/',query='chair birch green seat armchair',retrieved='2026-09-22',findings='Cantilever bentwood high-back armchair; structurally inconsistent with pictured four-legged dining chairs.',identity='rejected',used_dimensions=None),
 dict(id='SONGMICS',url='https://www.songmics.com/collections/laundry-racks/products/songmics-clothes-drying-rack-with-bamboo-hanging-rods-ullr516-517',query='bamboo clothes rack slatted bottom shelf',retrieved='2026-09-22',findings='Two-tier drying rack with bamboo rods differs from photographed single rail A-frame.',identity='rejected',used_dimensions=None),
 dict(id='RAGRUND',url='https://www.ikea.com/us/en/p/ragrund-chair-with-towel-rack-bamboo-90253074/',query='bamboo garment rack shelf',retrieved='2026-09-22',findings='Chair/towel stand; not the large garment rack.',identity='rejected',used_dimensions=None)]
catalogue=dict(sources=sources,queries_also_run=['black cabinet embossed horizontal ribs folding utility cabinet','site.3dwarehouse.sketchup.com bamboo clothes rack CH20 black cabinet'],conclusion='No exact SKU/variant verified. Do not transfer catalogue dimensions as measured dimensions.',priors=[dict(entity='room',quantity='height',value_m=2.8,range_m=[2.45,3.15],provenance='common indoor suspended-ceiling assumption, not measured'),dict(entity='table',quantity='height',value_m=.74,range_m=[.65,.82],provenance='common desk/dining table prior, cross-check only'),dict(entity='chair_near',quantity='seat_height',value_m=.45,range_m=[.38,.51],provenance='common chair prior, cross-check only')])
assets=dict(strategy_A='All geometry independently authored; external mesh files not opened.',strategy_B='Exact-identity verification precedes any mesh download. No qualifying exact assets.',objects=[dict(entity=i,mode='fallback_A',reason='Brand/model/variant cannot be verified from the available view; no similar mesh substitution',asset_downloaded=False,licence='not applicable, no asset adopted') for i,d,p,r,c in objects],controlled_comparison='If B remains all-fallback, geometry may equal A; do not claim an asset benefit.')
write_stage('agent_identify',{'catalogue.json':catalogue,'assets.json':assets},'Manufacturer evidence checked; uncertain identity prevents adopting exact geometry. Both branches use labelled common-size priors only.')
print('Authored observation and identification records')
