"""Bounded CPU evidence renders for the real-photo local-edit regression."""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'workflow'))
from r2s.refinement import write_render_binding
from r2s.core import atomic_json

packet = json.loads(Path(sys.argv[1]).read_text())
out = Path(packet['output_directory'])
src = {Path(a['path']).name: Path(a['path']) for a in packet['input_artifacts']['agent_model']}
shutil.copyfile(src['scene.json'], out / 'scene.json')
command = [packet['parameters']['blender'], '-b', str(src['model.blend']), '-t', str(packet['parameters'].get('threads', 4)),
           '--python-exit-code', '12', '--python', str(Path(__file__).with_name('render_refinement_probe_blender.py')), '--', str(out)]
subprocess.run(command, check=True, env={**os.environ, 'R2S_CPU': '1'})
write_render_binding(packet, out)
atomic_json(out / 'response.json', {'status': 'complete', 'evidence': ['Actual CPU renders, packed scene and image/model hashes'],
    'reasoning_summary': 'Rendered the unchanged comparison cameras and a chair diagnostic. No visual approval is generated by this script.',
    'artifacts': [p.name for p in out.iterdir() if p.is_file() and p.name not in {'packet.json', 'response.json', 'stdout.log', 'stderr.log', 'record.json'}]})
